### ISSUE TITLE
Do you want to support interstitial ads?

### ISSUE THREAD

**Issue by kyungjoongo** [duyduong/flutter_fbaudience_network#1]
Do you want to support interstitial ads?
Do you only support native banner ad?

**Comment by duyduong** [comment]
At this time, I just support native banner only.

I am waiting for Flutter to release iOS view equivalent to AndroidView

**Comment by karnadii** [comment]
Try this plugin, it work with banner and interstitial... But no native https://github.com/capripio/flutter_facebook_audience_network
