### ISSUE TITLE
i can not get display

### ISSUE THREAD

**Issue by sokkhimk** [duyduong/flutter_fbaudience_network#2]
FBNativeBannerAd(
            placementID: "1907860066008761_1918078734986894", // required params from Facebook
            padding: EdgeInsets.all(8.0), // content padding apply for native view
            margin: EdgeInsets.only(bottom: 20.0),
            style: AdStyle( // using AdStyle to change some views
              titleColor: Colors.white,
              socialTextColor: Colors.blueGrey,
              backgroundColor: Colors.black,
            ),
            onCreate: (NativeAdController controller) {
               controller.loadAd(); // Keep controller, then you can re-load the add any time
            },
          ),

===============================================
It show error like

aunching lib/main.dart on SM N910L in debug mode...
Initializing gradle...                                       0.6s
Resolving dependencies...                                    2.8s
Gradle task 'assembleDebug'...
Gradle task 'assembleDebug'... Done                          7.4s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                 11.8s
W/DisplayListCanvas( 4238): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
D/ViewRootImpl( 4238): MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=2
I/Timeline( 4238): Timeline: Activity_idle id: android.os.BinderProxy@f533a61 time:9814244
Syncing files to device SM N910L...                          1.4s

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on SM N910L is available at: http://127.0.0.1:61984/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
D/SecWifiDisplayUtil( 4238): Metadata value : none
I/System.out( 4238): ============= style {titleColor=#ffffffff, backgroundColor=#ff000000, socialTextColor=#ff607d8b}
W/ProxyCache( 4238): Unable to create external cache directory
I/ProxyCache( 4238): Proxy cache server started. Ping it...
D/ProxyCache( 4238): Open connection  to http://127.0.0.1:42940/ping
I/WebViewFactory( 4238): Loading com.google.android.webview version 72.0.3626.105 (code 362610500)
I/System.out( 4238): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 4238): (HTTPLog)-Static: isSBSettingEnabled false
D/ProxyCache( 4238): Accept new socket Socket[address=/127.0.0.1,port=33156,localPort=42940]
I/ProxyCache( 4238): Request to cache proxy:GetRequest{rangeOffset=0, partial=false, uri='ping'}
D/ProxyCache( 4238): Opened connections: 0
D/ProxyCache( 4238): Ping response: `ping ok`, pinged? true
I/cr_LibraryLoader( 4238): Time to load native libraries: 2 ms (timestamps 6076-6078)
I/chromium( 4238): [INFO:library_loader_hooks.cc(42)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader( 4238): Expected native library version number "72.0.3626.105", actual native library version number "72.0.3626.105"
D/AdInternalSettings( 4238): Test mode device hash: 6e9cf036-11b5-405a-ab57-b40ea4c58216
D/AdInternalSettings( 4238): When testing your app with Facebook's ad units you must specify the device hashed ID to ensure the delivery of test ads, add the following code before loading an ad: AdSettings.addTestDevice("6e9cf036-11b5-405a-ab57-b40ea4c58216");
W/System.err( 4238): remove failed: ENOENT (No such file or directory) : /data/user/0/com.example.tessapp/shared_prefs/WebViewChromiumPrefs.xml.bak
W/System.err( 4238): remove failed: ENOENT (No such file or directory) : /data/user/0/com.example.tessapp/shared_prefs/FBAdPrefs.xml.bak
D/SensorManager( 4238): registerListener :: 0, ICM20610 Acceleration Sensor, 200000, 0,
D/SensorManager( 4238): registerListener :: 3, ICM20610 Gyroscope Sensor, 200000, 0,
D/IS_UNITY( 4238): false
D/ViewRootImpl( 4238): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{cb89882 V.E...... R.....ID 0,0-0,0}
D/mali_winsys( 4238): new_window_surface returns 0x3000,  [2560x344]-format:1
D/libEGL  ( 4238): eglInitialize EGLDisplay = 0xb327e994
W/DisplayListCanvas( 4238): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
D/SensorManager( 4238): unregisterListener ::
D/SensorManager( 4238): unregisterListener ::
D/ViewRootImpl( 4238): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=2
D/libEGL  ( 4238): eglInitialize EGLDisplay = 0xb327ea84
D/libEGL  ( 4238): eglInitialize EGLDisplay = 0xb327ea84
D/SensorManager( 4238): registerListener :: 0, ICM20610 Acceleration Sensor, 200000, 0,
D/SensorManager( 4238): registerListener :: 3, ICM20610 Gyroscope Sensor, 200000, 0,
D/IS_UNITY( 4238): false
I/cr_BrowserStartup( 4238): Initializing chromium process, singleProcess=true
W/System.err( 4238): remove failed: ENOENT (No such file or directory) : /data/user/0/com.example.tessapp/shared_prefs/SDKIDFA.xml.bak
D/SecWifiDisplayUtil( 4238): Metadata value : none
D/SensorManager( 4238): unregisterListener ::
D/SensorManager( 4238): unregisterListener ::
D/ConnectivityManager( 4238): requestNetwork; getAppId(CallingUid) : 10268, CallingPid : 4238
I/System.out( 4238): (HTTPLog)-Static: isSBSettingEnabled false
I/System.out( 4238): (HTTPLog)-Static: isSBSettingEnabled false
W/cr_CrashFileManager( 4238): /data/user/0/com.example.tessapp/cache/WebView/Crash Reports does not exist or is not a directory
W/System.err( 4238): remove failed: ENOENT (No such file or directory) : /data/user/0/com.example.tessapp/shared_prefs/com.facebook.ads.FEATURE_CONFIG.xml.bak
I/System.out( 4238): nativeBannerAd onError The display format in the ad request does not match the display format specified for this placement. Each placement can only be used with a single display format. You can create multiple placements in order to use multiple display formats.
Lost connection to device.

============================================

How can I add banner facebook to flutter

**Comment by karnadii** [comment]
This plugin only support native banner, you should create placementid with type of native banner. The problem is your placementId.

**Comment by duyduong** [comment]
You can take a look closer to the ad error
`nativeBannerAd onError The display format in the ad request does not match the display format specified for this placement. Each placement can only be used with a single display format. You can create multiple placements in order to use multiple display formats.`
