### ISSUE TITLE
cannot build on Ios

### ISSUE THREAD

**Issue by cadinz** [duyduong/flutter_fbaudience_network#5]
this is the error output

   ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/tudeob/flutter_ios_dub2/ios/Runner/GeneratedPluginRegistrant.m:18:2: warning: missing submodule 'flutter_fbaudience_network.FlutterFBAudienceNetworkPlugin' [-Wincomplete-umbrella]
    #import <flutter_fbaudience_network/FlutterFBAudienceNetworkPlugin.h>
     ^      ~
    In file included from /Users/tudeob/flutter_ios_dub2/ios/Runner/GeneratedPluginRegistrant.m:18:
    /Users/tudeob/flutter_ios_dub2/build/ios/Debug-iphoneos/flutter_fbaudience_network/flutter_fbaudience_network.framework/Headers/FlutterFbaudienceNetworkPlugin.h:3:1: error: duplicate interface definition for class 'FlutterFbaudienceNetworkPlugin'
    @interface FlutterFbaudienceNetworkPlugin : NSObject<FlutterPlugin>
    ^
    In module 'flutter_fbaudience_network' imported from /Users/tudeob/flutter_ios_dub2/ios/Runner/GeneratedPluginRegistrant.m:18:
    /Users/tudeob/flutter_ios_dub2/build/ios/Debug-iphoneos/flutter_fbaudience_network/flutter_fbaudience_network.framework/Headers/FlutterFbaudienceNetworkPlugin.h:3:12: note: previous definition is here
    @interface FlutterFbaudienceNetworkPlugin : NSObject<FlutterPlugin>
               ^
    /Users/tudeob/flutter_ios_dub2/ios/Runner/GeneratedPluginRegistrant.m:52:4: error: unknown receiver 'FlutterFBAudienceNetworkPlugin'; did you mean 'FlutterFbaudienceNetworkPlugin'?
      [FlutterFBAudienceNetworkPlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterFBAudienceNetworkPlugin"]];
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       FlutterFbaudienceNetworkPlugin
    In file included from /Users/tudeob/flutter_ios_dub2/ios/Runner/GeneratedPluginRegistrant.m:18:
    /Users/tudeob/flutter_ios_dub2/build/ios/Debug-iphoneos/flutter_fbaudience_network/flutter_fbaudience_network.framework/Headers/FlutterFbaudienceNetworkPlugin.h:3:12: note: 'FlutterFbaudienceNetworkPlugin' declared here
    @interface FlutterFbaudienceNetworkPlugin : NSObject<FlutterPlugin>
               ^
    /Users/tudeob/flutter_ios_dub2/ios/Runner/GeneratedPluginRegistrant.m:52:4: error: definition of 'FlutterFbaudienceNetworkPlugin' must be imported from module 'flutter_fbaudience_network.FlutterFbaudienceNetworkPlugin' before it is required
      [FlutterFBAudienceNetworkPlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterFBAudienceNetworkPlugin"]];
       ^
    In module 'flutter_fbaudience_network' imported from /Users/tudeob/flutter_ios_dub2/ios/Runner/GeneratedPluginRegistrant.m:18:
    /Users/tudeob/flutter_ios_dub2/build/ios/Debug-iphoneos/flutter_fbaudience_network/flutter_fbaudience_network.framework/Headers/FlutterFbaudienceNetworkPlugin.h:3:12: note: previous definition is here
    @interface FlutterFbaudienceNetworkPlugin : NSObject<FlutterPlugin>
               ^
    1 warning and 3 errors generated.

what is the problem ..? : (

**Comment by casualcoder404** [comment]
Any progress in iOS implementation??

**Comment by cadinz** [comment]
its solved! Thanks
